USE KorenLibrary  


SELECT * FROM AniMektupGunluk$                    
UNION
SELECT * FROM ArastirmaYöntemi$
UNION
SELECT * FROM ATATÜRKÇÜLÜK$
UNION
SELECT * FROM BasinYayin$
UNION
SELECT * FROM bilim$
UNION
SELECT * FROM biyografi$
UNION
SELECT * FROM CocukGelisimi$
UNION
SELECT * FROM CocukSiirleri$
UNION
SELECT * FROM Çanakkale$
UNION
SELECT * FROM DenemeYazi$
UNION
SELECT * FROM destan$
UNION
SELECT * FROM DigerCocukKitaplari$
UNION
SELECT * FROM DinMezhepler$
UNION
SELECT * FROM DisDevletler$
UNION
SELECT * FROM divan$
UNION
SELECT * FROM DivanEdebiyati$
UNION
SELECT * FROM DortHalifeDonemi$
UNION
SELECT * FROM edebiyat$
UNION
SELECT * FROM egitim$
UNION
SELECT * FROM ekonomi$
UNION
SELECT * FROM ElSanatlari$
UNION
SELECT * FROM engelliler$
UNION
SELECT * FROM ErmeniMeselesi$
UNION
SELECT * FROM felsefe$
UNION
SELECT * FROM fýkýh$
UNION
SELECT * FROM folklor$
UNION
SELECT * FROM GuzelSanatlar$
UNION
SELECT * FROM hadis$
UNION
SELECT * FROM HalkEdebiyati$                
UNION
SELECT * FROM hukuk$
UNION
SELECT * FROM HzMuhammedinAshabi$
UNION
SELECT * FROM ilmihal$
UNION
SELECT * FROM karma$
UNION
SELECT * FROM KisiselGelisim$
UNION
SELECT * FROM kultur$
UNION
SELECT * FROM KuranýKerim$
UNION
SELECT * FROM KurtulusSavasi$
UNION
SELECT * FROM makale$
UNION
SELECT * FROM MantikÝstatistikBibliyografya$
UNION
SELECT * FROM MasallarHikayeler$
UNION
SELECT * FROM mesnevi$
UNION
SELECT * FROM MevlanaMesnevi$
UNION
SELECT * FROM milliyetcilik$
UNION
SELECT * FROM mimari$
UNION
SELECT * FROM muzik$
UNION
SELECT * FROM MuzikSinema$
UNION
SELECT * FROM NasrettinHocaDigerFikralar$
UNION
SELECT * FROM NasrettinHocaKeloglan$
UNION
SELECT * FROM OsmanlicaArapca$
UNION
SELECT * FROM OsmanlicaArapca$
UNION
SELECT * FROM OsmanliTarihi$
UNION
SELECT * FROM PeygamberlerIslamTarihi$
UNION
SELECT * FROM psikoloji$
UNION
SELECT * FROM RomanHikaye$
UNION
SELECT * FROM saglik$
UNION
SELECT * FROM SelcukluTarihi$
UNION
SELECT * FROM seyahat$
UNION
SELECT * FROM SeyyidKutup$
UNION
SELECT * FROM siir$
UNION
SELECT * FROM siyaset$
UNION
SELECT * FROM sosyoloji$
UNION
SELECT * FROM spor$
UNION
SELECT * FROM TanzimatEdebiyati$
UNION
SELECT * FROM tarih$
UNION
SELECT * FROM TarihOlayMesele$
UNION
SELECT * FROM tasavvuf$
UNION
SELECT * FROM TefsirDiniHikayeler$
UNION
SELECT * FROM tiyatro$
UNION
SELECT * FROM turk$
UNION
SELECT * FROM turkculuk$
UNION
SELECT * FROM TurkDili$
UNION
SELECT * FROM TurkiCumhuriyetler$
UNION
SELECT * FROM TurkiyeTarihi$
UNION
SELECT * FROM TurkYazarlarCocuk$
UNION
SELECT * FROM YabanciCocukRoman$
UNION
SELECT * FROM YabanciRoman$
UNION
SELECT * FROM YabanciSiirler$
UNION
SELECT * FROM YunusEmre$




--1. Create a new table:

CREATE TABLE book_unioned (
SIRA_NO INT NOT NULL IDENTITY(1,1),
YAZARIN_ADI  VARCHAR(50) NULL,
KÝTABIN_ADI VARCHAR(100) NULL,
YAYINEVÝ VARCHAR(50) NULL,
BASIM_TARÝHÝ VARCHAR(50) NULL,
SAYFA_SAYISI FLOAT NULL,
ADET FLOAT NULL,
DEMÝRBAÞ_NO FLOAT NULL,
TÜR VARCHAR(50) NULL
);

--2. Union all the other tables:

SELECT * FROM book_unioned


SET IDENTITY_INSERT book_unioned ON;

INSERT INTO book_unioned([SIRA_NO], [YAZARIN_ADI], [KÝTABIN_ADI], [YAYINEVÝ], [BASIM_TARÝHÝ], [SAYFA_SAYISI], [ADET], [DEMÝRBAÞ_NO], [TÜR])

SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM AniMektupGunluk$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM ArastirmaYöntemi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM ATATÜRKÇÜLÜK$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM BasinYayin$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM bilim$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM biyografi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM CocukGelisimi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝRBAÞ NO], [TÜR]   FROM CocukSiirleri$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM Çanakkale$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM DenemeYazi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM destan$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM DigerCocukKitaplari$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM DinMezhepler$
--UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM DisDevletler$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM divan$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM DivanEdebiyati$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM DortHalifeDonemi$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM edebiyat$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM egitim$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM ekonomi$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM ElSanatlari$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM engelliler$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM ErmeniMeselesi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM felsefe$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM fýkýh$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM folklor$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM GuzelSanatlar$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM hadis$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM HalkEdebiyati$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM hukuk$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM HzMuhammedinAshabi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM ilmihal$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM karma$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM KisiselGelisim$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM kultur$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]   FROM KuranýKerim$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM KurtulusSavasi$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM makale$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM MantikÝstatistikBibliyografya$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM MasallarHikayeler$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM mesnevi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM MevlanaMesnevi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM milliyetcilik$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM mimari$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM muzik$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM MuzikSinema$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM NasrettinHocaDigerFikralar$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM NasrettinHocaKeloglan$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM OsmanlicaArapca$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM OsmanliTarihi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM PeygamberlerIslamTarihi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM psikoloji$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM RomanHikaye$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM saglik$
-- ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM SelcukluTarihi$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM seyahat$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM SeyyidKutup$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM siir$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM siyaset$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM sosyoloji$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM spor$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM TanzimatEdebiyati$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTAP ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM tarih$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM TarihOlayMesele$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM tasavvuf$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM TefsirDiniHikayeler$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM tiyatro$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM turk$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM turkculuk$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM TurkDili$
UNION ALL
--SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM TurkiCumhuriyetler$
--UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR] FROM TurkiyeTarihi$  
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM TurkYazarlarCocuk$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝRBAÞ NO], [TÜR]   FROM YabanciCocukRoman$     
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM YabanciRoman$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝRBAÞ NO], [TÜR]  FROM YabanciSiirler$
UNION ALL
SELECT [S#NO], [YAZARIN ADI], [KÝTABIN ADI], YAYINEVÝ, [BASIM TARÝHÝ], [SAYFA SAYISI], ADET, [DEMÝR-BAÞ NO], [TÜR]  FROM YunusEmre$
SET IDENTITY_INSERT book_unioned OFF;



--EN ÇOK HANGÝ YAZARIN KÝTABI VARDIR?
SELECT TOP 1  YAZARIN_ADI, COUNT(YAZARIN_ADI) as yazar_adý
FROM book_unioned
GROUP BY YAZARIN_ADI
ORDER BY yazar_adý DESC

--TÜRE GÖRE EN ÇOK HANGÝ YAZARIN KÝTABI VARDIR?
SELECT TOP 1  YAZARIN_ADI, TÜR, COUNT(YAZARIN_ADI) as yazar_adý
FROM book_unioned
GROUP BY YAZARIN_ADI, TÜR
ORDER BY yazar_adý DESC

--TÜRE GÖRE EN AZ HANGÝ YAZARIN KÝTABI VARDIR?
SELECT TOP 1  YAZARIN_ADI, TÜR, COUNT(YAZARIN_ADI) as yazar_adý
FROM book_unioned
GROUP BY YAZARIN_ADI, TÜR
ORDER BY yazar_adý 

--EN AZ KÝTABI OLAN YAZAR HANGÝSÝDÝR?
SELECT TOP 2  YAZARIN_ADI, COUNT(YAZARIN_ADI) as yazar_adý
FROM book_unioned
GROUP BY YAZARIN_ADI
ORDER BY yazar_adý 

--EN ÇOK HANGÝ YAYINEVÝNÝN KÝTABI VARDIR?
SELECT TOP 1  YAYINEVÝ, COUNT(YAYINEVÝ) as yayýnevi_adý
FROM book_unioned
GROUP BY YAYINEVÝ
ORDER BY yayýnevi_adý DESC
--EN AZ HANGÝ YAYINEVÝNÝN KÝTABI VARDIR?
SELECT TOP 2  YAYINEVÝ, COUNT(YAYINEVÝ) as yayýnevi_adý
FROM book_unioned
GROUP BY YAYINEVÝ
ORDER BY yayýnevi_adý 
--EN AZ HANGÝ BASIM TARÝHLÝ YILDIR?
SELECT TOP 1  BASIM_TARÝHÝ, COUNT(BASIM_TARÝHÝ) as BasýmTarihi
FROM book_unioned
GROUP BY BASIM_TARÝHÝ
ORDER BY BasýmTarihi
--EN ÇOK HANGÝ BASIM TARÝHLÝ YILDIR?
SELECT TOP 1  BASIM_TARÝHÝ, COUNT(BASIM_TARÝHÝ) as BasýmTarihi
FROM book_unioned
GROUP BY BASIM_TARÝHÝ
ORDER BY BasýmTarihi DESC
--SAYFA SAYISI EN ÇOK OLAN KÝTAP HANGÝSÝDÝR?
SELECT TOP 1  KÝTABIN_ADI, SAYFA_SAYISI 
FROM book_unioned
GROUP BY KÝTABIN_ADI, SAYFA_SAYISI 
ORDER BY SAYFA_SAYISI DESC
--SAYFA SAYISI EN AZ OLAN KÝTAP HANGÝSÝDÝR?
SELECT   KÝTABIN_ADI, SAYFA_SAYISI 
FROM book_unioned
GROUP BY KÝTABIN_ADI, SAYFA_SAYISI 
ORDER BY SAYFA_SAYISI
--KÝTAPLARIN ORTALAMA SAYFA SAYISI KAÇTIR?
SELECT  AVG(SAYFA_SAYISI ) as ort_sayfa
FROM book_unioned

--TOPLAM KAÇ TÜR KÝTAP VARDIR?
SELECT  COUNT(DISTINCT  TÜR)
FROM book_unioned

--HANGÝ TÜRDEN KAÇ KÝTAP VARDIR?
SELECT TÜR, COUNT(TÜR) as türr
FROM book_unioned
GROUP BY TÜR
ORDER BY türr DESC

--EN ÇOK HANGÝ TÜRDE KÝTAP VARDIR?
SELECT TOP 1 TÜR, COUNT(TÜR) as türr
FROM book_unioned
GROUP BY TÜR
ORDER BY türr DESC

--EN AZ HANGÝ TÜRDE KÝTAP VARDIR?
SELECT TOP 1 TÜR, COUNT(TÜR) as türr
FROM book_unioned
GROUP BY TÜR
ORDER BY türr 
